---
name: reminder_app
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.8.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  freezed_annotation: ^0.12.0
  flutter_bloc: ^6.1.1
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  google_sign_in: ^4.5.6
  get_it: ^5.0.3
  injectable: ^1.0.7
  flushbar: ^1.10.4
  uuid: ^2.2.2
  kt_dart: ^0.8.0
  auto_route: ^0.6.9
  shimmer: ^1.1.2
  json_annotation: ^3.1.1
  rxdart: ^0.25.0
  flutter_hooks: ^0.15.0
  provider: ^4.3.2+3
  numberpicker: ^1.3.0
  flutter_slidable: ^0.5.7
  fl_chart: ^0.12.2
  test: ^1.15.7
  bloc_test: ^7.1.0
  mockito: ^4.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: null
  freezed: ^0.12.7
  lint: ^1.3.0
  injectable_generator: ^1.0.7
  json_serializable: ^3.5.1
flutter:
  uses-material-design: true
