---
name: reminder_app
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  freezed_annotation: ^0.12.0
  flutter_bloc: ^6.1.1
  cloud_firestore: ^1.0.1
  firebase_core: ^1.0.1
  firebase_core_web: ^1.0.1
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.1
  get_it: ^5.0.3
  injectable: ^1.0.7
  uuid: ^2.2.2
  kt_dart: ^0.8.0
  shimmer: ^1.1.2
  json_annotation: ^3.1.1
  rxdart: ^0.25.0
  flutter_hooks: ^0.15.0
  provider: ^4.3.2+3
  numberpicker: ^1.3.0
  flutter_slidable: ^0.5.7
  fl_chart: ^0.20.1
  test: ^1.15.7
  bloc_test: ^7.1.0
  mockito: ^4.1.4
  rive: ^0.6.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  freezed: ^0.12.7
  lint: ^1.3.0
  injectable_generator: ^1.0.7
  json_serializable: ^3.5.1
flutter:
  uses-material-design: true
  assets:
    - assets/run.riv
