---
name: reminder_app
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.8.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  freezed_annotation: ^0.12.0
  flutter_bloc: ^4.0.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  get_it: ^4.0.0
  injectable: ^1.0.4
  flushbar: ^1.10.4
  uuid: ^2.2.2
  kt_dart: ^0.7.0+1
dev_dependencies:
  build_runner: null
  freezed: ^0.12.1
  lint: ^1.2.0
  injectable_generator: ^1.0.4
flutter:
  uses-material-design: true
